baseURL = 'https://martinaspeli.net/'
languageCode = 'en-gb'
title = 'Martin Aspeli'

[params]
title = "Martin Aspeli"
author = "Martin Aspeli"
description = ""
profilePicture = "images/profile.jpg"
readMore = true

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

theme = "anatole"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"
